### ISSUE TITLE
No current media session for custom receiver with own cast.receiver.media.Player implementation 

### ISSUE THREAD

**Issue by CAMOBAP795** [googlecast/CastReferencePlayer#26]
I fighting with a problem with "No current media session" on Android sender for custom Chromecast receiver app

I attached minimal receiver app which reproduce this problem (this app didn't play actually just logging to console)

Android sender log

```
10-17 18:49:38.599: E/ws_audio_test(32498): Caused by: java.lang.IllegalStateException: No current media session
10-17 18:49:38.599: E/ws_audio_test(32498):     at org.sample.share.test.cast.WebSocketAudioServerExample.play(WebSocketAudioServerExample.java:151)
10-17 18:49:38.599: E/ws_audio_test(32498):     at org.sample.share.test.ChromeCastSampleActivity.onTogglePlay(ChromeCastSampleActivity.java:139)
10-17 18:49:38.599: E/ws_audio_test(32498):     at java.lang.reflect.Method.invoke(Native Method)
10-17 18:49:38.599: E/ws_audio_test(32498):     at java.lang.reflect.Method.invoke(Method.java:372)
10-17 18:49:38.599: E/ws_audio_test(32498):     at android.view.View$1.onClick(View.java:4005)
10-17 18:49:38.599: E/ws_audio_test(32498):     at android.view.View.performClick(View.java:4759)
10-17 18:49:38.599: E/ws_audio_test(32498):     at android.widget.CompoundButton.performClick(CompoundButton.java:125)
10-17 18:49:38.599: E/ws_audio_test(32498):     at android.view.View$PerformClick.run(View.java:19770)
10-17 18:49:38.599: E/ws_audio_test(32498):     at android.os.Handler.handleCallback(Handler.java:739)
10-17 18:49:38.599: E/ws_audio_test(32498):     at android.os.Handler.dispatchMessage(Handler.java:95)
10-17 18:49:38.599: E/ws_audio_test(32498):     at android.os.Looper.loop(Looper.java:135)
10-17 18:49:38.599: E/ws_audio_test(32498):     at android.app.ActivityThread.main(ActivityThread.java:5237)
10-17 18:49:38.599: E/ws_audio_test(32498):     at java.lang.reflect.Method.invoke(Native Method)
10-17 18:49:38.599: E/ws_audio_test(32498):     at java.lang.reflect.Method.invoke(Method.java:372)
10-17 18:49:38.599: E/ws_audio_test(32498):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
10-17 18:49:38.599: E/ws_audio_test(32498):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
10-17 18:49:38.599: E/ws_audio_test(32498): Caused by: java.lang.IllegalStateException: No current media session
10-17 18:49:38.599: E/ws_audio_test(32498):     at com.google.android.gms.cast.internal.zzn.zzajz(Unknown Source)
10-17 18:49:38.599: E/ws_audio_test(32498):     at com.google.android.gms.cast.internal.zzn.zzc(Unknown Source)
10-17 18:49:38.599: E/ws_audio_test(32498):     at com.google.android.gms.cast.RemoteMediaPlayer$19.zza(Unknown Source)
10-17 18:49:38.599: E/ws_audio_test(32498):     at com.google.android.gms.cast.RemoteMediaPlayer$19.zza(Unknown Source)
10-17 18:49:38.599: E/ws_audio_test(32498):     at com.google.android.gms.internal.zzqc$zza.zzb(Unknown Source)
10-17 18:49:38.599: E/ws_audio_test(32498):     at com.google.android.gms.internal.zzqm.zzf(Unknown Source)
10-17 18:49:38.599: E/ws_audio_test(32498):     at com.google.android.gms.internal.zzqm.zzd(Unknown Source)
10-17 18:49:38.599: E/ws_audio_test(32498):     at com.google.android.gms.internal.zzqr.zzd(Unknown Source)
10-17 18:49:38.599: E/ws_audio_test(32498):     at com.google.android.gms.internal.zzqp.zzd(Unknown Source)
10-17 18:49:38.599: E/ws_audio_test(32498):     at com.google.android.gms.cast.RemoteMediaPlayer.play(Unknown Source)
10-17 18:49:38.599: E/ws_audio_test(32498):     at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.play(VideoCastManager.java:1588)
10-17 18:49:38.599: E/ws_audio_test(32498):     at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.play(VideoCastManager.java:1611)
10-17 18:49:38.599: E/ws_audio_test(32498):     at org.sample.share.test.WebSocketAudioServerExample.play(WebSocketAudioServerExample.java:149)
10-17 18:49:38.599: E/ws_audio_test(32498):     ... 15 more
```

Custom receiver log

```
[  0.554s] [cast.receiver.IpcChannel] Opening platform websocket
cast_receiver.js:68  [  0.654s] [cast.receiver.CastReceiverManager] Version: 2.0.0.0045
player.js:690 [2016-10-17T15:49:11.866Z] registerErrorCallback
player.js:690 [2016-10-17T15:49:11.870Z] registerEndedCallback
player.js:690 [2016-10-17T15:49:11.873Z] registerLoadCallback
player.js:690 [2016-10-17T15:49:11.899Z] Starting receiver manager
cast_receiver.js:68  [  0.737s] [cast.receiver.IpcChannel] Opening message bus websocket
cast_receiver.js:68  [  0.815s] [cast.receiver.IpcChannel] IpcChannel opened
cast_receiver.js:68  [  0.823s] [cast.receiver.CastMessageBus] Dispatching CastMessageBus message
cast_receiver.js:68  [  0.834s] [cast.receiver.CastReceiverManager] Underlying message bus is open
cast_receiver.js:68  [  0.839s] [cast.receiver.IpcChannel] IPC message sent: {"namespace":"urn:x-cast:com.google.cast.system","senderId":"SystemSender","data":"{\"type\":\"ready\",\"statusText\":\"Application is starting\",\"activeNamespaces\":[\"urn:x-cast:com.google.cast.media\",\"urn:x-cast:com.google.cast.inject\"],\"version\":\"2.0.0\",\"messagesVersion\":\"1.0\"}"}
cast_receiver.js:68  [  0.845s] [cast.receiver.IpcChannel] IPC message sent: {"namespace":"urn:x-cast:com.google.cast.system","senderId":"SystemSender","data":"{\"type\":\"startheartbeat\",\"maxInactivity\":30}"}
cast_receiver.js:68  [  0.902s] [cast.receiver.IpcChannel] Received message: {"data":"{\"applicationId\":\"E49B86C9\",\"applicationName\":\"PAMediaShareCustomReceiver\",\"closedCaption\":{},\"deviceCapabilities\":{\"bluetooth_supported\":false,\"display_supported\":true,\"hi_res_audio_supported\":false},\"launchingSenderId\":\"d5557a8f-5135-0ef6-2198-6459b226044f.107:org.webaudio.share.test-12\",\"messagesVersion\":\"1.0\",\"sessionId\":\"86C22879-3B13-40C4-BF1B-CB52F1483A26\",\"type\":\"ready\",\"version\":\"1.20.66189\"}","namespace":"urn:x-cast:com.google.cast.system","senderId":"SystemSender"}
cast_receiver.js:68  [  0.910s] [cast.receiver.CastMessageBus] Dispatching CastMessageBus message
cast_receiver.js:68  [  0.920s] [cast.receiver.IpcChannel] IPC message sent: {"namespace":"urn:x-cast:com.google.cast.system","senderId":"SystemSender","data":"{\"type\":\"setappstate\",\"statusText\":\"Application is starting\"}"}
cast_receiver.js:68  [  0.930s] [cast.receiver.CastReceiverManager] Dispatching CastReceiverManager system ready event
player.js:690 [2016-10-17T15:49:12.114Z] onReady
cast_receiver.js:68  [  0.941s] [cast.receiver.IpcChannel] Received message: {"data":"{\"level\":1.0,\"muted\":false,\"type\":\"volumechanged\"}","namespace":"urn:x-cast:com.google.cast.system","senderId":"SystemSender"}
cast_receiver.js:68  [  0.945s] [cast.receiver.CastMessageBus] Dispatching CastMessageBus message
cast_receiver.js:68  [  0.966s] [cast.receiver.CastReceiverManager] Dispatching system volume changed event [1, false]
cast_receiver.js:68  [  0.975s] [cast.receiver.IpcChannel] Received message: {"data":"{\"type\":\"visibilitychanged\"}","namespace":"urn:x-cast:com.google.cast.system","senderId":"SystemSender"}
cast_receiver.js:68  [  0.981s] [cast.receiver.CastMessageBus] Dispatching CastMessageBus message
cast_receiver.js:68  [  0.989s] [cast.receiver.CastReceiverManager] Ignoring visibility changed event, state is already null
cast_receiver.js:68  [  0.991s] [cast.receiver.IpcChannel] Received message: {"data":"{\"type\":\"standbychanged\"}","namespace":"urn:x-cast:com.google.cast.system","senderId":"SystemSender"}
cast_receiver.js:68  [  0.993s] [cast.receiver.CastMessageBus] Dispatching CastMessageBus message
cast_receiver.js:68  [  0.997s] [cast.receiver.IpcChannel] Received message: {"data":"{\"senderId\":\"d5557a8f-5135-0ef6-2198-6459b226044f.107:org.webaudio.share.test-12\",\"type\":\"senderconnected\",\"userAgent\":\"Android CastSDK,9877248,Mi 4i,ferrari,5.0.2\"}","namespace":"urn:x-cast:com.google.cast.system","senderId":"SystemSender"}
cast_receiver.js:68  [  1.005s] [cast.receiver.CastMessageBus] Dispatching CastMessageBus message
cast_receiver.js:68  [  1.018s] [cast.receiver.CastReceiverManager] Dispatching CastReceiverManager sender connected event [d5557a8f-5135-0ef6-2198-6459b226044f.107:org.webaudio.share.test-12]
cast_receiver.js:68  [  1.022s] [cast.receiver.CastMessageBus] Registering sender [urn:x-cast:com.google.cast.media, d5557a8f-5135-0ef6-2198-6459b226044f.107:org.webaudio.share.test-12]
cast_receiver.js:68  [  1.027s] [cast.receiver.CastMessageBus] Registering sender [urn:x-cast:com.google.cast.inject, d5557a8f-5135-0ef6-2198-6459b226044f.107:org.webaudio.share.test-12]
cast_receiver.js:68  [  1.031s] [cast.receiver.IpcChannel] Received message: {"data":"{\"requestId\":1,\"type\":\"GET_STATUS\"}","namespace":"urn:x-cast:com.google.cast.media","senderId":"d5557a8f-5135-0ef6-2198-6459b226044f.107:org.webaudio.share.test-12"}
cast_receiver.js:68  [  1.037s] [cast.receiver.CastMessageBus] Dispatching CastMessageBus message
cast_receiver.js:68  [  1.039s] [cast.receiver.MediaManager] MediaManager message received
cast_receiver.js:68  [  1.044s] [cast.receiver.MediaManager] Dispatching MediaManager getStatus event
cast_receiver.js:68  [  1.047s] [cast.receiver.MediaManager] onGetStatus
cast_receiver.js:68  [  1.053s] [cast.receiver.MediaManager] onGetStatus: {"requestId":1}
cast_receiver.js:68  [  1.056s] [cast.receiver.MediaManager] Sending status message to d5557a8f-5135-0ef6-2198-6459b226044f.107:org.webaudio.share.test-12
cast_receiver.js:68  [  1.063s] [cast.receiver.IpcChannel] IPC message sent: {"namespace":"urn:x-cast:com.google.cast.media","senderId":"d5557a8f-5135-0ef6-2198-6459b226044f.107:org.webaudio.share.test-12","data":"{\"type\":\"MEDIA_STATUS\",\"status\":[],\"requestId\":1}"}
player.js:690 [2016-10-17T15:49:12.251Z] getCurrentTimeSec
cast_receiver.js:68  [ 21.430s] [cast.receiver.IpcChannel] Received message: {"data":"{\"requestId\":2,\"type\":\"QUEUE_LOAD\",\"items\":[{\"media\":{\"contentId\":\"http:\\/\\/192.168.88.59:7777\",\"streamType\":\"BUFFERED\",\"contentType\":\"application\\/x-ws-f32\",\"metadata\":{\"metadataType\":3,\"title\":\"WebAudio Stream\",\"artist\":\"Artist ?\"},\"duration\":999.999},\"autoplay\":true,\"startTime\":0,\"preloadTime\":20}],\"repeatMode\":\"REPEAT_OFF\",\"startIndex\":0}","namespace":"urn:x-cast:com.google.cast.media","senderId":"d5557a8f-5135-0ef6-2198-6459b226044f.107:org.webaudio.share.test-12"}
cast_receiver.js:68  [ 21.439s] [cast.receiver.CastMessageBus] Dispatching CastMessageBus message
cast_receiver.js:68  [ 21.447s] [cast.receiver.MediaManager] MediaManager message received
cast_receiver.js:68  [ 21.455s] [cast.receiver.MediaManager] Dispatching MediaManager queueLoad event
cast_receiver.js:68  [ 21.472s] [cast.receiver.MediaManager] Dispatching MediaManager load event
cast_receiver.js:68  [ 21.479s] [cast.receiver.MediaManager] Load message received:{"type":"LOAD","requestId":2,"mediaSessionId":0,"customData":null,"media":{"contentId":"http://192.168.88.59:7777","streamType":"BUFFERED","contentType":"application/x-ws-f32","metadata":{"metadataType":3,"title":"WebAudio Stream","artist":"Artist ?"},"duration":999.999},"autoplay":true,"currentTime":0}
player.js:690 [2016-10-17T15:49:32.667Z]  -> {"type":"load","na":false,"defaultPrevented":false,"Ec":true,"data":{"type":"LOAD","requestId":2,"mediaSessionId":0,"customData":null,"media":{"contentId":"http://192.168.88.59:7777","streamType":"BUFFERED","contentType":"application/x-ws-f32","metadata":{"metadataType":3,"title":"WebAudio Stream","artist":"Artist ?"},"duration":999.999},"autoplay":true,"currentTime":0},"senderId":"d5557a8f-5135-0ef6-2198-6459b226044f.107:org.webaudio.share.test-12"}
player.js:690 [2016-10-17T15:49:32.676Z] load
```

Custom receiver code:

[custom_receiver.zip](https://github.com/googlecast/CastReferencePlayer/files/533984/custom_receiver.zip)

Because there is no reference sample for `cast.receiver.media.Player`
Any help will be appreciated

**Comment by alex-schwartzman** [comment]
@CAMOBAP795  I have the same problem now - I implemented cast.receiver.media.Player with the use of shaka player, all the messaging in urn:x-cast:com.google.cast.media namespace seems to be OK for me, but the RemoteMediaPlayer never recognizes received messages and never knows that the media session started. 

Maybe that could be an option contribute to this project by our own implementation of custom receiver, and let @entertailion to review it.

**Comment by alex-schwartzman** [comment]
@CAMOBAP795 here is the sample player implementation, which does not show any video, just simulates the states change. So it loads immediately after load() call and after 3 seconds of buffering it starts playback of the media 120 seconds long. On the Android sender, RemoteMediaPlayer changes its state accordingly.


```
 this.myPlayer = {
            getSecondsEpoch:  function(){
                return new Date().getTime()/1000;
            },
            startTime: 0,
            mState:null,
            editTracksInfo: function(data){
                console.log('editTracksInfo'+data);
            },
            getRelativeTime: function(){
                return this.getSecondsEpoch() - this.startTime;
            },
            getCurrentTimeSec: function(){
                var relativeTime = this.getRelativeTime();
                var currentTime = 0;
                if(relativeTime > 3){
                    currentTime = relativeTime - 3;
                }
                console.log('getCurrentTimeSec '+currentTime);
                return currentTime;
            },
            getDurationSec: function(){
                console.log('getDurationSec');
                return 120;
            },
            getState: function(){
                var state =  'PLAYING';
                console.log('getState '+state);
                return state;
            },
            getVolume: function(){
                var volume = new cast.receiver.media.Volume();
                volume.level=0.7;
                volume.muted=false;
                console.log('getVolume '+volume);
                return volume;
            },
            load: function(contentId, autoplay, opt_time, opt_tracksInfo, opt_onlyLoadTracks){
                console.log('load '+contentId+' autoplay: '+autoplay);
                this.startTime = this.getSecondsEpoch();
                if(this.mLoadCallback!=null){
                    this.mLoadCallback();
                }
            },
            pause: function(){
                console.log('pause');
            },
            play: function(){
                console.log('play');
                this.startTime = getSecondsEpoch;
            },
            mEndedCallback:null,
            registerEndedCallback: function(endedCallback){
                console.log('registerEndedCallback(endedCallback)');
                this.mEndedCallback=endedCallback;
            },
            mErrorCallback:null,
            registerErrorCallback: function(errorCallback){
                console.log('registerErrorCallback(errorCallback)');
                this.mErrorCallback=errorCallback;
            },
            mLoadCallback:null,
            registerLoadCallback: function(loadCallback){
                console.log('registerLoadCallback(loadCallback)');
                this.mLoadCallback=loadCallback;
            },
            reset: function(){
                console.log('reset');
            },
            seek: function(){
                console.log('seek');
            },
            setVolume: function(volume){
                console.log('setVolume '+volume);
            },
            unregisterEndedCallback: function(){
                console.log('unregisterEndedCallback');
                this.mEndedCallback=null;
            },
            unregisterErrorCallback: function(){
                console.log('unregisterErrorCallback');
                this.mErrorCallback=null;
            },
            unregisterLoadCallback: function(){
                console.log('unregisterLoadCallback');
                this.mLoadCallback=null;
            },
            init: function(){
                this.startTime=this.getSecondsEpoch();
                console.log(this.getCurrentTimeSec());
                console.log(this.getState());
                console.log(this.getVolume());

            }



      }

      this.myPlayer.init();
      window.mediaManager = new cast.receiver.MediaManager(this.myPlayer);
```
